if(SYNMODELS_BUILD_PYBINDINGS OR SYNMODELS_BUILD_ALL)
    message(STATUS "Generating Python Bindings")
    include(LoadPybind)
    LoadPybind()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
    add_subdirectory(extras/py_synmodels)
endif()

if(SYNMODELS_BUILD_TESTS OR SYNMODELS_BUILD_ALL)
    message(STATUS "Generating tests")
    enable_testing()
    add_subdirectory(tests)
endif()

if(SYNMODELS_BUILD_BENCH OR SYNMODELS_BUILD_ALL)
    message(STATUS "Generating benchmarks")
    add_subdirectory(extras/benchmarking)
endif()