---
name: Respond Code Coverage
# Schema: https://json.schemastore.org/github-action.json

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Calculate Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Respond Repository
              uses: actions/checkout@v6

            - name: Install gcovr
              run: pip install gcovr

            - name: Build and Test Project
              run: >
                  cmake --workflow --preset test-debug-static-workflow

            - name: Generate gcovr report
              run: |
                  gcovr -r . --xml-pretty -o coverage.xml

            - name: Upload Code Coverage Report
              uses: actions/upload-artifact@v7
              with:
                  name: code-coverage-report
                  path: coverage.xml

            - name: Generate Coverage Badge
              uses: GaelGirodon/ci-badges-action@v1
              with:
                  gist-id: 10e746e28df5d23e91689b01493435a0
                  token: ${{secrets.GIST_BADGE_TOKEN}}
