name: Release Project

on:
    push:
        tags:
            - "v*.*.*"
env:
    BUILD_TYPE: Release

jobs:
    build:
        name: Building Debian Ubuntu Packages
        runs-on: ubuntu-latest
        strategy:
            matrix:
                build-variant: [shared, static]
        steps:
            - name: Checkout Respond Repository
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

            - name: Build Debian Package
              run: |
                  echo "Building Linux"
                  cmake --workflow --preset package-release-debian-${{matrix.build-variant}}-workflow
              shell: bash
            - name: Create a zip file with specific files/folders
              shell: powershell
              run: |
                  Compress-Archive -Path "${{ github.workspace }}/build/${{ matrix.build-variant }}/*.deb" -DestinationPath "${{ matrix.build-variant }}.zip"
            - name: Upload Debian Package to Release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: "${{ matrix.build-variant }}.zip"
                  file_glob: true
                  tag: ${{ github.ref }}
