name: Respond Unit Testing
# Schema: https://json.schemastore.org/github-action.json

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unit-testing:
        name: Testing ${{matrix.os}} ${{matrix.build-variant}} build
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                build-variant: [shared, static]
        steps:
            - name: Checkout Respond Repository
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

            - name: Install MinGW
              if: matrix.os == 'windows-latest'
              uses: msys2/setup-msys2@v2
              with:
                  msystem: MINGW64

            - name: Run Testing Workflow
              run: |
                  if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                      echo "Testing Linux"
                      cmake --workflow --preset test-debug-linux-${{matrix.build-variant}}-workflow
                  elif [ "${{ matrix.os }}" == "windows-latest" ]; then
                      echo "Testing Microsoft"
                      cmake --workflow --preset test-debug-microsoft-${{matrix.build-variant}}-workflow
                  fi
              #   elif [ "${{ matrix.os }}" == "macos-latest" ]; then
              #       echo "Testing MacOS"
              #       brew install gcc
              #       cmake --workflow --preset test-debug-linux-${{matrix.build-variant}}-workflow
              timeout-minutes: 10
              shell: bash
