name: Windows Respond Unit Testing
# Schema: https://json.schemastore.org/github-action.json

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unit-testing:
        name: Testing ${{matrix.os}} ${{matrix.build-variant}} build
        runs-on: ${{matrix.os}}
        defaults:
            run:
                shell: pwsh
        strategy:
            matrix:
                os: [windows-latest] # , macos-latest
                build-variant: [shared, static]
        steps:
            - name: Checkout Respond Repository
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

            - name: Run Testing Workflow
              run: |
                  cmake --workflow --preset test-debug-${{matrix.build-variant}}
              timeout-minutes: 10
